### ISSUE TITLE
/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook

### ISSUE THREAD

**Issue by kahrkunne** [Lazy-Newb-Pack/LNP-Linux-legacy#1]
Quite simple: starting the thing then pressing Play Dwarf Fortress! writes "/bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook" in the terminal it was started from twice, and does nothing else.

**Comment by kahrkunne** [comment]
kahr[~]>/bin/sh --version 
GNU bash, version 4.3.30(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Here, that might help you a bit

**Comment by kahrkunne** [comment]
Downgrading to bash 4.2 works (but causes it to give a different error, namely "xdg-terminal: configured terminal program 'rxvt-unicode-256color' not found or not executable"), but this is not wanted, as bash 4.2 is very old and probably very vulnerable.

**Comment by lethosor** [comment]
Does DF work if you launch the `df` or `dfhack` script directly?

**Comment by BeauBouchard** [comment]
I believe this was #2, the issue was reproduced if you used the GCC 4.9.1 / qt 5 version of the package, from the github release.  There was a typo in the startlnp file left in from when I was testing something.  The downloads on the website were tested and worked. The two github packages have been fixed. Thank you again for bringing this to our attention.

**Comment by kusayuzayushko** [comment]
Get this error too

> ./startlnp  
> /bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook
> /bin/sh --version  
> GNU bash, version 4.3.33(1)-release (x86_64-unknown-linux-gnu)

**Comment by ald0n** [comment]
same here.
GNU bash, version 4.3.33(1)-release (x86_64-pc-linux-gnu)

**Comment by Plukers** [comment]
I can confirm that. 
Same error with GNU bash, version 4.3.33(1)-release (x86_64-pc-linux-gnu)

**Comment by miffedmap** [comment]
> GNU bash, version 4.3.33(1)-release (x86_64-redhat-linux-gnu)
> /lib64/libreadline.so.6.3
> /lib64/libc.so.6 -> libc-2.20.so

... and I **don't** have this problem. which distro are you all using?

I looked into this couple weeks ago and user reports associate this with an upgrade to bash 4.3, but only because it indirectly involves a change to the readline version linked (note the `rl_` prefix in the missing symbol).  an old bug (now fixed) in python also turned up which manifests this way.

It probably has to do with whatever is being used to generate a binary from the python sources, perhaps an old python is getting bundled? maybe readline should get static-linked in?

**Comment by ald0n** [comment]
> which distro are you all using?

Using gentoo ~amd64 with 3.19.0 kernel, sys-libs/readline-6.3_p8-r2

**Comment by miffedmap** [comment]
which libc version does your system have?

**Comment by ald0n** [comment]
> which libc is that?

sys-libs/glibc-2.20-r2

**Comment by miffedmap** [comment]
``` bash
# objdump -T /lib64/libreadline.so | grep -i rl_signal_event_hook
0000000000249088 g    DO .bss   0000000000000008  Base        rl_signal_event_hook
```

can you check this (adjusting paths)?

**Comment by ald0n** [comment]
> can you check this (adjusting paths)?

objdump -T /lib64/libreadline.so.6 | grep -i rl_signal_event_hook
000000000024ae48 g    DO .bss   0000000000000008  Base        rl_signal_event_hook

**Comment by miffedmap** [comment]
and can you verify that you can:
- run `df` directly without issues
- the error raises when running `PyLNP` and not from the other stuff in `startlnp`

**Comment by ald0n** [comment]
> run df directly without issues

suddenly
df_linux/df: line 10: df_linux/distro_fixes.sh: No such file or directory

> the error raises when running PyLNP and not from the other stuff in startlnp 

neither PyLNP nor startlnp show any errors

**Comment by miffedmap** [comment]
> suddenly:  df_linux/df: line 10: df_linux/distro_fixes.sh: No such file or directory

the `distro_fixes.sh` issue is unrelated, running from another directory <del>might  be</del> is broken.

> neither PyLNP nor startlnp show any errors

you reported earlier that `startlnp` gives an error about `rl_signal_event_hook`, are you still seeing that error or not?

**Comment by ald0n** [comment]
> the distro_fixes.sh issue is unrelated, running from another directory might be broken.

when im trying to start df directly **after** _PyLNP/startlnp_,

> [distro_fixes] INFO Checking whether any ARCH/distro specific fixes are required...
> [distro_fixes] INFO OS: Gentoo
> [distro_fixes] INFO ARCH: x86_64
> [distro_fixes] INFO VER: 2.2
> [distro_fixes] INFO DF_ARCH: 32-bit
> [distro_fixes] INFO DF_BIN_LOCATION: /home/ald0n/games/rougelike/04024r2-x64/df_linux/libs/Dwarf_Fortress
> [distro_fixes] WARN 32bit 'Dwarf_Fortress' on 64bit OS detected. see ./df script for fix using LD_PRELOAD.
> [distro_fixes] INFO Done
> Gtk-Message: Failed to load module "canberra-gtk-module"
> libpng warning: iCCP: bad parameters to zlib
> libpng error: bad parameters to zlib

and gtk window tell me that it can't load any from data/art

> Tileset not found
> Not found: data/art/Phoebus_16x16.png

but i have files there

> -rwxrwxr-x 1   67K Feb  8 13:03 Phoebus_16x16.png
> -rwxrwxr-x 1   66K Feb  8 13:03 Phoebus_16x16_Diagonal.png
> -rwxrwxr-x 1   57K Feb  8 13:03 Phoebus_16x16_Smooth.png
> -rwxrwxr-x 1   67K Feb  8 13:03 Phoebus_16x16_Symbol.png
> -rwxrwxr-x 1   69K Feb  8 13:03 Phoebus_16x16_TextBackground.png
> -rwxrwxr-x 1   69K Feb  8 13:03 Phoebus_16x16_TextClean.png
> -rw-rw-r-- 1   75K Feb  8 13:03 Phoebus_16x16_text.png
> -rw-rw-r-- 1   70K Feb  8 13:03 Vanilla DF - 24x - Items.png
> -rwxrwxr-x 1  350K Feb  8 13:03 font.TTF
> -rwxrwxr-x 1  608K Feb  8 13:03 font_dejavu_sans.ttf
> -rwxrwxr-x 1  3.1K Feb  8 13:03 mouse.bmp
> -rwxrwxr-x 1   249 Feb  8 13:03 mouse.png
> -rw-rw-r-- 1  4.4K Feb  8 13:03 shadows.png
> -rw-rw-r-- 1   11K Feb  8 13:03 text_12x16.png

Running df from _startlnp_ or _PyLNP_ gives the same error

> /bin/sh: symbol lookup error: /bin/sh: undefined symbol: rl_signal_event_hook

also (maybe it helps)

> -rwxr-xr-x 1 root root 27K Feb 25 12:10 /usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
> lrwxrwxrwx 1 root root 26 Feb 25 12:10 /usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so -> libcanberra-gtk3-module.so
> 
> _media-libs/libcanberra_
> Installed versions:  0.30-r4 (alsa gtk gtk3 sound -gnome -gstreamer -oss -pulseaudio -tdb -udev)
> _media-libs/libpng_
> Installed versions:  1.6.16 (apng -neon -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="32 64 -x32")
> _sys-libs/zlib_
> Installed versions:  1.2.8-r1(-minizip -static-libs ABI_MIPS="-n32 -n64 -o32" ABI_PPC="-32 -64" ABI_S390="-32 -64" ABI_X86="32 64 -x32")

**Comment by miffedmap** [comment]
a few seperate issues are getting mixed up here. @ald0n , first let's try to get you running df from the command line, please hop over to #23 and let's deal with that there. then we'll come back to the trickier issue with readline (which I haven't figured out yet).

**Comment by Pidgeot** [comment]
Apologies for not coming in here sooner; I keep forgetting to look on Github since I keep PyLNP over at Bitbucket.

> It probably has to do with whatever is being used to generate a binary from the python sources, perhaps an old python is getting bundled? maybe readline should get static-linked in?

Right, so, about this: Once I was initially made aware of this issue, I did much of the same research as you appear to have done, and discovered the [Python bug](http://bugs.python.org/issue20374) that I'm assuming you also found. This states the bug should have been fixed in Python 2.7.8 and up.

Since 2.7.8 was not in the repository on my build VMs (Linux Mint), I proceeded to create new VMs for building, and chose Gentoo as a base, since that seemed to be the best way to guarantee access to the latest versions. This was initially done for 0.8, starting with 0.9.1, these are running only Python 2.7.9 and 3.3.5, both of which have this bug fixed.

I have, however, just noticed that these systems are still on readline 6.2 and bash 4.2; the newer versions aren't part of the stable set of packages offered by Gentoo yet. I will try to force an upgrade of those before I build a new set of binaries later today, _hopefully_ this will finally squash this bug.

EDIT: This _seems_ to have done the trick; I can't reproduce the error after a rebuild. The error should be fixed with 0.9.5, which I plan to release layer today.

**Comment by miffedmap** [comment]
That's great @Pidgeot. I wasn't aware upstream (i.e. you) was actually the one distributing the binary (It's not checked in to your repo, but that [makes sense](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/issues/21)). I thought @BeauBouchard used pyinstaller (or whatever) to generate a binary as part of his packaging efforts.

I did some testing with gentoo as well and to get bash 4.3 you do need to pull from `testing` (I've never used gentoo before, it's... full of its own ways) and was then able to reproduce. I couldn't trigger the issue with binaries I made myself (on fedora) though, so that was a dead end (and I Failed to rebuild a working binary of PyLNP myself).

But it sounds like the next release will clear this up and along the way we got gentoo working out of the box with help from @ald0n. so good news all around.

**Comment by Pidgeot** [comment]
@miffedmap Yes, I upload binaries for all platforms to the [downloads page](https://bitbucket.org/Pidgeot/python-lnp/downloads). In cases where a pack is behind on updates, it can be a good idea to try the latest one there, in case the issue is already fixed.

**Comment by lethosor** [comment]
I haven't heard reports of this still being a problem, but please report this in the [new repo](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux) if it is.
