### ISSUE TITLE
"undefined symbol: _ZN17file_compressorst15set_buffer_infoEPclS0_l" on "offloading items" screen

### ISSUE THREAD

**Issue by vrutkovs** [Lazy-Newb-Pack/LNP-Linux-legacy#3]
Fedora 21, recompiled libgraphics.so and get

```
./libs/Dwarf_Fortress: symbol lookup error: ./libs/Dwarf_Fortress: undefined symbol: _ZN17file_compressorst15set_buffer_infoEPclS0_l
```

during 'Offloading screen' on world generation screen

**Comment by vrutkovs** [comment]
Recompiling libgraphics.so is not needed it seems, adding 'export LD_PRELOAD=/lib/libz.so' to df scripts fixed it

See http://www.bay12forums.com/smf/index.php?topic=140966.msg5518005#msg5518005

**Comment by lethosor** [comment]
Yeah, there tend to be problems with symbols not being available in custom libgraphics builds. Did you compile from the source included with DF or from Baughn/Dwarf-Fortress--libgraphics-?

**Comment by Ramblurr** [comment]
Now that Fedora 21 is out I'm getting this problem too with the recompiled libgraphics (from [svenstaro's repo](https://github.com/svenstaro/dwarf_fortress_unfuck)). However if I use the vanilla libgraphics, I get "libGLEW.so.1.9: cannot open shared object file: No such file or directory" because Fedora 21 has moved to libGLEW-1.10.
