### ISSUE TITLE
Failed to read JSON from PyLNP.user

### ISSUE THREAD

**Issue by benfairless** [Lazy-Newb-Pack/LNP-Linux-legacy#6]
```
Note: Failed to read JSON from PyLNP.user, ignoring data - error details follow
Traceback (most recent call last):
  File "/home/michael/Desktop/df/python_lnp/build/lnp/out00-PYZ.pyz/core.json_config", line 26, in __init__
IOError: [Errno 2] No such file or directory: u'PyLNP.user'
```

My name isn't Michael, which means there is also some hard-coded directory in there somewhere. :smile: 

Found in version v0.40.15r1 running on Fedora 20.

**Comment by BeauBouchard** [comment]
XD, I will bring this up to @Pidgeot , PyLNP.user is a file which stores the user preferences. I didn't get the error when I ran it on Ubuntu. I will look into it, and thank you for reporting this

**Comment by BeauBouchard** [comment]
Are you able to run the package at all?

**Comment by Pidgeot** [comment]
The path in the stack trace simply comes from the directory the build took place in; it has nothing to do with the file being accessed.

This particular file stores user settings; if this is your first time running the launcher, the message is expected, since you don't have any such settings. (In the event that you _did_ have settings, this message would let you know they couldn't be read, and therefore they weren't applied.)

The message is completely harmless and the program will work just fine without the file. I'll likely change the error message in the near future to give a better message in the case where the file doesn't exist, though.

**Comment by BeauBouchard** [comment]
@Pidgeot Thank you for explaining that. :+1:

**Comment by benfairless** [comment]
Thanks  for the quick response guys :+1:
